create extension if not exists pgcrypto with schema extensions;

create table if not exists public.invite_config (
  id smallint primary key default 1 check (id = 1),
  seed text not null,
  rotation_epoch timestamptz not null,
  interval_days smallint not null default 7 check (interval_days between 1 and 90),
  grace_hours smallint not null default 24 check (grace_hours between 0 and 72),
  updated_at timestamptz not null default now()
);

alter table public.invite_config enable row level security;
revoke all on table public.invite_config from anon, authenticated, public;
grant select, update on table public.invite_config to service_role;

insert into public.invite_config (id, seed, rotation_epoch, interval_days, grace_hours)
values (
  1,
  encode(extensions.gen_random_bytes(32), 'hex'),
  '2026-07-19 15:00:00+00',
  7,
  24
)
on conflict (id) do nothing;

create table if not exists public.auth_attempts (
  id bigint generated by default as identity primary key,
  attempt_key text not null,
  attempt_kind text not null check (attempt_kind in ('invite', 'register', 'login')),
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists auth_attempts_lookup_idx
  on public.auth_attempts (attempt_key, attempt_kind, created_at desc);

alter table public.auth_attempts enable row level security;
revoke all on table public.auth_attempts from anon, authenticated, public;
grant select, insert, delete on table public.auth_attempts to service_role;
grant usage, select on sequence public.auth_attempts_id_seq to service_role;

-- The old profile ID was stored per browser. Profiles are intentionally reset
-- so every new row can be tied one-to-one to a real Supabase Auth user.
delete from public.team_members;

alter table public.team_members
  add column if not exists login_name text;

alter table public.team_members
  alter column id set default auth.uid(),
  alter column login_name set not null;

alter table public.team_members
  drop constraint if exists team_members_login_name_format;

alter table public.team_members
  add constraint team_members_login_name_format
  check (
    char_length(login_name) between 1 and 30
    and login_name = btrim(login_name)
  );

create unique index if not exists team_members_login_name_unique
  on public.team_members (login_name);

alter table public.team_members
  drop constraint if exists team_members_id_fkey;

alter table public.team_members
  add constraint team_members_id_fkey
  foreign key (id) references auth.users(id) on delete cascade;

create or replace function public.is_active_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.team_members
    where id = (select auth.uid())
  );
$$;

revoke all on function public.is_active_member() from public, anon;
grant execute on function public.is_active_member() to authenticated;

create or replace function public.protect_calendar_event_creator()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := (select auth.uid());
  else
    new.created_by := old.created_by;
  end if;
  return new;
end;
$$;

drop trigger if exists calendar_events_protect_creator on public.calendar_events;
create trigger calendar_events_protect_creator
before insert or update on public.calendar_events
for each row execute function public.protect_calendar_event_creator();

drop policy if exists team_can_create_team_members on public.team_members;
drop policy if exists team_can_delete_team_members on public.team_members;
drop policy if exists team_can_read_team_members on public.team_members;
drop policy if exists team_can_update_team_members on public.team_members;

create policy active_members_can_read_team_members
on public.team_members
for select
to authenticated
using ((select public.is_active_member()));

revoke all on table public.team_members from anon, authenticated;
grant select on table public.team_members to authenticated;
grant select, insert, update, delete on table public.team_members to service_role;

drop policy if exists team_can_create_calendar_events on public.calendar_events;
drop policy if exists team_can_delete_calendar_events on public.calendar_events;
drop policy if exists team_can_read_calendar_events on public.calendar_events;
drop policy if exists team_can_update_calendar_events on public.calendar_events;

create policy active_members_can_read_calendar_events
on public.calendar_events
for select
to authenticated
using ((select public.is_active_member()));

create policy active_members_can_create_calendar_events
on public.calendar_events
for insert
to authenticated
with check (
  (select public.is_active_member())
  and created_by = (select auth.uid())
);

create policy active_members_can_update_calendar_events
on public.calendar_events
for update
to authenticated
using ((select public.is_active_member()))
with check ((select public.is_active_member()));

create policy active_members_can_delete_calendar_events
on public.calendar_events
for delete
to authenticated
using ((select public.is_active_member()));

revoke all on table public.calendar_events from anon, authenticated;
grant select, insert, update, delete on table public.calendar_events to authenticated;
